version: 2.1
jobs:
  
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello"
  say-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say world"
          command: "echo World!"
  say-my-name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say my name"
          command: echo $myname
    environment:
      myname: test-job
workflows:
  say-hello-workflow:
    jobs:
      - say-my-name
      - say-hello
      - say-world:
          requires:
            - say-hello

